name: letter_boxed_engine
description: A starting point for Dart libraries or applications.
version: 0.0.5
repository: https://github.com/lucas-marianno/Encaixado

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  assets:
    - assets/pt_valid_words_only.json
    - assets/en_valid_words_only.json
    - assets/games.json