name: letter_boxed_engine
description: A starting point for Dart libraries or applications.
version: 0.0.4
repository: https://github.com/lucas-marianno/Encaixado

environment:
  sdk: ^3.5.3

assets:
  - assets/

# Add regular dependencies here.
dependencies:


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
